### PR TITLE
Fix incoherent output and turn off my janky experimental GPT2

### LINKED ISSUE #123: Incoherent output since merging #118
Since merging #118, all output is totally garbled, as below.

pwsh_2020-02-09_20-08-31

Running on Windows 10 1909, GTX 970 and Ryzen 3600X. Tried PyTorch 1.4 and nightly, GPU and CPU, default model and 744 base model. Works fine on the previous commit.

### PR DESCRIPTION
**Pull request by Akababa**
Fixes #123 - confirmation that it works on other platforms and other peoples' systems would be helpful.
Add setting gpt2-experimental to use my experimental GPT2 and set it to off by default.
Skip the model selection menu when DEBUG_GPT2 is set.

### CODE REVIEW

**Comment by Akababa** [comment]
Good idea, i'll do that.

**Comment by MikkoMMM** [comment]
Hmm, it doesn't seem to work as I had imagined it would:
```
[mikko@localhost Clover-Edition]$ MODEL="model_v5_pytorch" python3.7 play.py 
ATTENTION: Clover-Edition has just gone through some major updates. You will have to reinstall if you are still on the old version. Many things have been changed. Please read the README.md or https://github.com/cloveranon/Clover-Edition

03/29/2020 23:28:51 - INFO - Python Prompt Toolkit has been imported. This enables a number of editing features but may cause bugs for colab users.
03/29/2020 23:28:52 - INFO - Cuda Available: True    Force CPU: False    Precision: 16-bit
03/29/2020 23:28:52 - INFO - Colab detected: False
...
03/29/2020 23:28:52 - WARNING - Using DEBUG MODE! This is just for devs to quickly check a small (124M) GPT2 model with poor output. Selected pretrained model_v5_pytorch
03/29/2020 23:28:52 - INFO - Using device=cuda, checkpoint=model_v5_pytorch, dtype=torch.float16
Traceback (most recent call last):
  File "play.py", line 755, in <module>
    gm = GameManager(get_generator())
  File "play.py", line 62, in get_generator
    repetition_penalty=settings.getfloat("rep-pen"),
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2generator.py", line 221, in __init__
    self.tokenizer = tokenizer_class.from_pretrained(str(self.checkpoint_path))
  File "/usr/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 302, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/usr/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 444, in _from_pretrained
    tokenizer.init_inputs = init_inputs
UnboundLocalError: local variable 'tokenizer' referenced before assignment

A fatal error has occurred. 
Traceback (most recent call last):
  File "play.py", line 755, in <module>
    gm = GameManager(get_generator())
  File "play.py", line 62, in get_generator
    repetition_penalty=settings.getfloat("rep-pen"),
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition/gpt2generator.py", line 221, in __init__
    self.tokenizer = tokenizer_class.from_pretrained(str(self.checkpoint_path))
  File "/usr/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 302, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/usr/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 444, in _from_pretrained
    tokenizer.init_inputs = init_inputs
UnboundLocalError: local variable 'tokenizer' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "play.py", line 770, in <module>
    if gm and gm.story:
NameError: name 'gm' is not defined
code 1
```

**Comment by Akababa** [comment]
That's because the environment variable is a string, not a Path. transformers library has pre-trained GPT2 models under various string keys, like "gpt2" (124M) and "gpt2-xl" (1.5B), and also allows you to load your own pretrained GPT2 if you pass it a python Path object. Thus to maintain unambiguity, you can't use the same environment variable for both loading methods - that's why setting MODEL=model_v5_pytorch doesn't load it from your models folder. It's asking the transformers library for that pretrained model, which it doesn't have.

On the other hand, if you set MODEL to one of the string keys on [this page](https://huggingface.co/transformers/_modules/transformers/modeling_gpt2.html), it should load the generic pretrained GPT2.

**Comment by Akababa** [comment]
Pushed another commit, hopefully that should clear things up.

**Comment by MikkoMMM** [comment]
Okay. MODEL_FOLDER indeed seems to work like how I was thinking. Giving TRANSFORMERS_PRETRAINED_MODEL gibberish still crashes the thing but I suppose whoever uses it might understand better. I still don't think I do since I don't know what the regular model is if it's not gpt2-xl (which seemed to hang).

**Comment by Akababa** [comment]
The following (from that link in my previous comment) should work for TRANFORMERS_PRETRAINED_MODEL:
```python
GPT2_PRETRAINED_MODEL_ARCHIVE_MAP = {
    "gpt2": "https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-pytorch_model.bin",
    "gpt2-medium": "https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-medium-pytorch_model.bin",
    "gpt2-large": "https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-large-pytorch_model.bin",
    "gpt2-xl": "https://s3.amazonaws.com/models.huggingface.co/bert/gpt2-xl-pytorch_model.bin",
    "distilgpt2": "https://s3.amazonaws.com/models.huggingface.co/bert/distilgpt2-pytorch_model.bin",
}
``

**Pull request merged**
