### PR TITLE
Fix story formatting

### PR DESCRIPTION
**Pull request by devfag**
This is a continuation on PR #111 

I believe a good portion of the reason why people are complaining that our fork doesn't have as good text generation is due to how we format text. Specifically, other forks output their text in a style more akin to a novel or short story. This PR seeks to solve this issue.

I have attempted to fix our existing formatting woes, which include:
- Not adding a newline when the result is a continuation of the story prompt
- Separating dialogue sections into separate paragraphs in the style of novels (when multiple strings of dialogue occur in succession, they will be newlined)
- Separating dialogue that starts a sentence into a new paragraph in the style of novels.
- Fixing text fill so that it properly wraps paragraphs independently of eachother

Please stress test this. There are many edge cases to be accounted for.

### CODE REVIEW

**Comment by MikkoMMM** [comment]
It is as I thought. When the story is still being generated, the wrapping goes wrong. After that it fixes itself. https://framapic.org/iZFRUQmKzD2H/mUd75O0sW4pD.png

We COULD of course print out the whole context+prompt+already generated text after each token generation, so it would definitely use the same API, but that sounds kind of dumb to me.

**Comment by MikkoMMM** [comment]
DURING the story generation, it still doesn't format the context+prompt: https://framapic.org/1VQMyAMpOdel/pxBvNNnOs7Y7.png

The issue there seems to go away after it's been formatted with your new changes.

However, I kind of liked how the context and the prompt had an empty line between them. Often I would see the context being written in a different style, thus warranting its own paragraph.

I did find this issue already, though. Writing in as a context: "This is a context." and as a prompt: "This is a prompt." results in "This is a context.This is a prompt." on the screen.

**Comment by MikkoMMM** [comment]
This seems erroneous: https://framapic.org/iJJSUwhxagJZ/zyv2kBswgqse.png

**Comment by MikkoMMM** [comment]
In the regular back-and-forth with the computer every time someone talks it has seemed to be on its own line. However, this was right after story generation:
https://framapic.org/GzBpf6wg1tLC/NL0qQkDP1GND.png

**Comment by MikkoMMM** [comment]
If I remove the "You " in the prompt-toolkit mode, it still puts an ending period (I suppose I did have an ending space; I didn't test without yet):
https://framapic.org/igEX8kOfNV6v/Iq6GAiSHqXZR.png

I thought this was supposed to be the "verbatim" mode where it shouldn't really do any modifications to the input.

**Comment by MikkoMMM** [comment]
Even after the generation:
https://framapic.org/16jwuDgNncpB/vKidKow8okSK.png

**Comment by devfag** [comment]
I'll remove the period in verbatim mode. The context and prompt seem to not be formatted the same, I can modify that.

I only want to put the generated first result on the same line when it's a clear continuation of a fragmented sentence at the end of the prompt. it makes it a lot easier to follow. I feel like the differing colors is enough to indicate this isn't the same text.

**Comment by MikkoMMM** [comment]
> I only want to put the generated first result on the same line when it's a clear continuation of a fragmented sentence at the end of the prompt. it makes it a lot easier to follow. I feel like the differing colors is enough to indicate this isn't the same text.

If you referred to:

> However, I kind of liked how the context and the prompt had an empty line between them. Often I would see the context being written in a different style, thus warranting its own paragraph.

I was NOT talking about the AI's answer. I talked about the context and the prompt given by the player. Those seem to be on the same line and without so much as a space between them, in your version. And THEY aren't differentiated by color: they are both in the user-text color.

If, for instance, you were referring to
> https://framapic.org/iJJSUwhxagJZ/zyv2kBswgqse.png

instead, I was pointing out the incorrect-looking wrapping in the AI's text. I suppose my last reply was about the same issue, now that I look at it.

**Comment by devfag** [comment]
Ah, sorry, I misread. I can put the context and the prompt onto separate lines.

**Comment by MikkoMMM** [comment]
I think that now if there is no prompt, there will be two empty lines after the context instead of the usual one.

**Comment by devfag** [comment]
Good point. Fixing now.

**Comment by MikkoMMM** [comment]
I think I may have found the issue why I've sometimes seen incorrect wrapping. My clue was that it only seemed to happen right after the initial prompt. I see you have a fill_text function which tries to solve the issues with newlines being passed to the wrapping function, but there's something that can slip past it: if the '\n' is given as the sep parameter.

Look here:
```
        wtext = text1 + '\u200D' + text2 if text2 is not None else text1
        wtext = fill_text(wtext, width)
```
The separator is transformed into a different character entirely, which fill_text isn't detecting. It then wraps the text treating it like any normal character, wrapping the two texts concatenated together. But then later on this is done:
```
        wtext = wtext.split('\u200D')
        text1 = wtext[0]
```
And thus, a now we have a text1 which is (presumably) correctly wrapped, a separator which isn't yet taken into account, and text2 which has its first line wrapped as if it was going to come right after text1, but instead it finds itself after the sep which might be newlines instead. In which case it's incorrectly wrapped.

**Comment by MikkoMMM** [comment]
If the AI's output starts with a punctuation mark, there shouldn't be a space before it if it's after the initial prompt, like happened here:

> The source of your anger is before you , the source of your

**Comment by MikkoMMM** [comment]
I've also seen compound words being cut with a space but unless I missed some other place where whitespace stripping is done, I don't think the AI consistently adds a beginning space if it's not writing a compound word. So that might be unreasonable to fix.

**Pull request merged**
