### PR TITLE
Pytorch conversion

### PR DESCRIPTION
**Pull request by renekris**
From #21. Makes conversion to Pytorch quick.

image

dump - where the finalized files go after conversion
gpt2_model - where you put the files to be converted
merge_vocab - merge & vocab file that gets transferred into the dump folder after conversion.

convert the model.bat - should be run after putting the pre-converted model into gpt2_model

### CODE REVIEW

**Comment by cloveranon** [comment]
Why did you remove AOPs convert to half precision code? I didn't realize that was there and it should be optional until we test it more. But I think it should make the models half the size and we mostly use 16bit anyway.

Are the vocabulary files standard for all GPT2 models? I do not think they are.

**Comment by renekris** [comment]
I removed the half-precision code because it was polluting the dump folder with an extra file, which would've made anons confused, Can be obviously added back...

It seemed like the vocabulary files were all the same, but I'm not sure anymore.

**Comment by cloveranon** [comment]
Alright sorry before I merge I'd like to do some experiments and figure this out. It's taking me forever to download new models on my shit internet though.

**Comment by renekris** [comment]
Let me know what you find out! Interested in it myself

**Comment by cloveranon** [comment]
Your code isn't bad or anything. I just thought it would be better to simplify the options to the original script and ended up doing a lot more, resolving the whole issue: https://github.com/cloveranon/Clover-Edition/commit/74740894324656e81065bc018df7e3bf044b4575

**Pull request closed without merging**
