### PR TITLE
Revised the arrow key and home/end key functionalities in the multiline editor

### PR DESCRIPTION
**Pull request by MikkoMMM**
The up and down arrow keys now visually (on "visual rows" instead of lines ending in a newline) follow an imaginary vertical line up/down, starting from where they were first pressed. If there is a shorter row than what the movement started at, for that row the cursor goes to the end of that line. If up is pressed on the first row, the cursor jumps to the beginning of the whole text, and if down is pressed on the last row, the cursor jumps to the end of the whole text.

For home/end, they now first take to the start/end of the visual row, but if already at that point, they go on to move the cursor to the start/end of the actual line.

What worries me is mostly that it's now heavily reliant on the getTermWidth function so if there are popular consoles for which it doesn't work, we are in trouble. Luckily, the editor can be tested by itself: `python inline_editor.py`, and there's an example text ready there with long enough lines for hopefully testing the functionality well. And for making sense of my poor explanation.

### CODE REVIEW

**Comment by devfag** [comment]
Thank you, this was much needed and appreciated. Can't review until I'm home from work but I will check it out.

**Comment by MikkoMMM** [comment]
I think I should add something in the spirit of openness; a possible issue one may encounter when testing. When pressing up or down, the cursor may on rare occasions go to a wrong column by a key or few. I think that the "textf.buffer.on_cursor_position_changed" event doesn't always trigger when a key is pressed. I manually invoke it for several key combinations, but it's not very realistic to do it for all of them.

I also made the functions cursor_col and cursor_row in case the built-in ones had some kind of multithreading weirdness going on, but I don't know. Now it's such a rare event that I would be unsure about whether I really even saw it happening, so I can't even be certain it exists any longer with the attempted solutions in place.

**Comment by MikkoMMM** [comment]
@devfag Why did you remove the "raise ModuleNotFoundError" in https://github.com/cloveranon/Clover-Edition/pull/98? Now, I think, that if prompt-toolkit is set to false, it will not load the fallback readline library which is supposed to fix the issue of escape characters appearing when pressing arrow keys and so on on Linux. I readded it in this attempt to resolve the merge conflict.

Anyway, is once more nobody going to check this pull request?

**Comment by devfag** [comment]
Looking at it now, was just fixing the issues you raised.

The whole point is that import raises either `ImportError` or `ModuleNotFoundError` when a module cannot be imported, so adding it is redundant.

**Comment by MikkoMMM** [comment]
The raising of the error serves a purpose, though. It then can fall back to using readline even if it doesn't naturally raise it from trying to import libraries that aren't there because the setting of not having the prompt-toolkit used overrides importing them. Maybe you already understood seeing that first line of yours. I suppose the section could possibly be refactored somehow to not be so confusing, though.

**Comment by devfag** [comment]
@MikkoMMM These changes seem to be fine. I am indeed having the issue with vertical lines that you described, although in my case it happened before editing anything.

A change that is unrelated: I was thinking, in the spirit of chat clients like discord and slack, shift+enter is newline and regular enter is sending the message, or in our case, committing the changes. How do you feel about that?

**Comment by devfag** [comment]
Yeah, I think we need to re-address how these dependencies are being resolved. Let's leave it for now; this is a PR all on its own.

**Comment by MikkoMMM** [comment]
I personally dislike the keybindings you described in the current scenarios where the multiline editor is used; though for regular prompts that sounds like a good way to still allow multiple lines if the user really wanted to. Maybe at one point or another are going to want user configuration for keybindings solve these matters of opinion.

**Comment by MikkoMMM** [comment]
Hmm, the cursor should jump to the end of the prompt when the editor opens up. At that point also update_stored_pos(None) is manually invoked, so it should really start out with the correct vertical lining. Maybe I'm just not understanding from that description. Anyway, if it's some kind of a consistent and not the randomly happening sort of an issue, feel free to raise an issue.

I did take this arrow key when word wrapping functionality upstream to Prompt Toolkit itself and they also would like having it implemented. It's apparently fairly complex to do properly so it may take some time until we have a better solution than this mess, though.

**Pull request merged**
