### PR TITLE
Add settings menu

### LINKED ISSUE #82: Settings menu
It would be nice to be able to start a game with the settings you want right away. I'm going to set up a submenu in the top menu that lets you see and modify the existing settings before you start a game.

### PR DESCRIPTION
**Pull request by devfag**
Adds a settings menu which can be used to access the settings from the main menu. Also consolidates the user-modifiable settings into a dict in `getconfig` that maps the settings names to both their description and their default value. This is what's now printed from when the help text appears, in order to make sure the settings menu and help prompt are always consistent. Also adds a `/settings` command to the main game that can be used to access the same menu.

Closes #82

### CODE REVIEW

**Comment by AtaIanta** [comment]
image
Shouldn't 11) Cancel be renamed to Exit? It can suggest canceling all changes made in settings.
Also in powershell the input is not visible due to coloring.

**Comment by AtaIanta** [comment]
and current settings don't display in /help menu

**Comment by devfag** [comment]
I'll modify the text and merge on my remote and then bring it back in

**Comment by devfag** [comment]
Let me know if there's any issues.

**Pull request merged**
