### PR TITLE
The story now prints as it's being generated, if in prompt_toolkit. closes #110

### LINKED ISSUE #110: You is stripped in Colab mode
I wrote: > You test

It at least output as the "final prompt": > test.

### PR DESCRIPTION
**Pull request by MikkoMMM**
closes #110

### CODE REVIEW

**Comment by devfag** [comment]
You say that it prints as it's being generated. I'm using prompt-toolkit on a local copy and I don't quite understand what you mean. It seems to be printing the same way as before?

**Comment by devfag** [comment]
Also, this has been bugging me for a while: the initial prompt usually ends in an unfinished sentence. The generator usually finishes this sentence, but we print the second half of the sentence on a new line. Could we make it so that if the generated text begins with a lowercase character, that we instead print with a space separator instead of a newline?

**Comment by devfag** [comment]
Other than those two issues, I haven't encountered any bugs.

**Comment by MikkoMMM** [comment]
Weird that it's not doing it for you. Are you sure that colab-mode = off and prompt-toolkit = on, and that you don't have any strange merge conflicts? After all, there is `output(generated.text, "ai-text")` in gpt2generator.py's token generation loop.

I had my share of problems already with the styling of the story start with this PR. I could have sent some kind of an up arrow press escape code to get the text coming after clear_lines to go on the topmost cleared line, not the one after. However, the styling is different almost everywhere else; where we do have an empty line between what comes after. I figured it would be too much spaghetti code if I had some kind of a check for whether we need to start outputting right on the next line or if we can have that empty line between. So I even changed the story's start to have that empty line too. It might need yet another round of refactoring to do what you want in a sensible way after this PR, I'm worrying.

**Comment by devfag** [comment]
The I/O code has definitely gotten messier now that we essentially support two different methods: vanilla and prompt-toolkit. I think we don't worry about it for now, but soon employ use of the strategy pattern and some sort of I/O object factory to clean it up / separate it into two more managable objects.

**Comment by devfag** [comment]
I haven't been able to get it to print in the way you describe on either GPU or CPU. I'm chopping it up to my computer being fast enough.

**Comment by MikkoMMM** [comment]
Well, I suppose since there don't appear to be game-breaking problems, I'll merge.

**Comment by devfag** [comment]
Sorry, I wasn't very clear: the `closes #110` needs to be in the description of pr, not the title. I added it.

**Pull request merged**
