### PR TITLE
Incorporating the Python Prompt Toolkit branch

### PR DESCRIPTION
**Pull request by MikkoMMM**
I heard that it might not work in Colab, so it's an optional thing (and even forcibly disabled in Colab for now at least). However, for those that do have it, the doors are open for more advanced input schemes and stuff.

Edit: You need to use `pip install -r optional-requirements.txt` to install the Python Prompt Toolkit which is what this pull request is pretty much all about; though it required a lot of overhauling to get two palettes to work at the same time so some testing in the "classic" mode is also a good idea.

For now there's only a new "finalizing input" prompt. Edit: And a new color scheme and a multiline editor.

I'm not exactly happy with how much extra fluff there's starting to be in play.py, but it's maybe good enough to start the conversation about the future of the UI(s) for Clover.

### CODE REVIEW

**Comment by cloveranon** [comment]
I have merged in this pull request https://github.com/cloveranon/Clover-Edition/pull/46 to the branch [prompt-toolkit](https://github.com/cloveranon/Clover-Edition/tree/prompt-toolkit). See https://github.com/cloveranon/Clover-Edition/issues/47

**Comment by MikkoMMM** [comment]
I tried to solve the merge conflict. Now I just need people to look at this and determine whether it's ready to be merged to master.

**Comment by devfag** [comment]
We got issues

```python
Traceback (most recent call last):
  File "play.py", line 683, in <module>
    generator = get_generator()
  File "play.py", line 43, in get_generator
    colors["loading-message"],
  File "utils.py", line 161, in output
    col1 = ptcolors[col1] if col1 and ptcolors[col1] else ""
  File "D:\Program Files\Python\lib\configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: '7;34'
```

This happens when I start up the game. This issue is caused wherever the `output` function is passed a `colors[str]` value instead of a regular string. You forgot to change over the outputs.

I don't think this should have been merged into master without more review.

**Comment by devfag** [comment]
Deleted previous comment due to it being a broken pull.

Getting this error instead on `master`:
```python
Traceback (most recent call last):
  File "play.py", line 659, in <module>
    generator = get_generator()
  File "play.py", line 29, in get_generator
    "loading-message", end="\n\n"
  File "D:\Users\Dan\Code\Python\Clover-Edition\utils.py", line 157, in output
    print_formatted_text(to_formatted_text(text1, col1), end='')
NameError: name 'print_formatted_text' is not defined
```

**Comment by devfag** [comment]
There is no `print_formatted_text` in `master`.

**Comment by devfag** [comment]
Not sure what this function is supposed to do.

There also is no `to_formatted_text`, which is used by `print_formatted_text`

**Comment by MikkoMMM** [comment]
Line 55 of https://github.com/cloveranon/Clover-Edition/blob/master/utils.py

**Comment by devfag** [comment]
Ah, I had the toolkit on and not installed. My bad.

**Comment by devfag** [comment]
We may want to run a try-except on the prompt toolkit import and disable it if the resource can't be found.

**Comment by MikkoMMM** [comment]
There IS one; lines 50 and 61. Do you know why it isn't working?

**Comment by devfag** [comment]
we're not setting the boolean to false when it fails, so that might be part of it

**Comment by devfag** [comment]
i think the .ini by default has prompt toolkit set to "on" which would also cause an issue

**Comment by MikkoMMM** [comment]
Yes. I figured if it can automatically disable itself if not available for the system, it would be a nice default setting.

**Comment by devfag** [comment]
Okay, made it catch both `ImportError` and `ModuleNotFoundError`, and then set the prompt-toolkit flag to false when it's caught. Works now.

**Comment by devfag** [comment]
Line 610 in play gives me this error:

```python
Traceback (most recent call last):
  File "play.py", line 660, in <module>
    play(generator)
  File "play.py", line 610, in play
    action = prompt("For REAL: ", default="%s" % action)
TypeError: 'str' object is not callable
```
what is this used for, and why is it trying to use `prompt` as a callable?

**Comment by MikkoMMM** [comment]
You have an incorrectly merged file, I think. Line 610 uses ptprompt, not prompt:
https://github.com/cloveranon/Clover-Edition/blob/master/play.py

**Comment by devfag** [comment]
Oh, damn. Good catch. Anyways, what is this used for anyways?

**Comment by MikkoMMM** [comment]
I suppose it could probably be switched to use the input_line function. It's something that can finalize prompts; the postprocessing of input still makes some grammatical mistakes from time to time. The ! command, I suppose, kind of overlaps in its use cases also making it less useful than it was initially.

**Comment by devfag** [comment]
Oh I see, it's a correction measure. I mean, if we're using the prompt toolkit, couldn't we just insert the "You " before an action and then let the user decide if they want to keep it?

**Comment by devfag** [comment]
It just seems a little weird to have to confirm every action

**Comment by MikkoMMM** [comment]
Yeah, well, that was the other idea I had for it. I suppose with the ! command there also the use cases are limited enough that having the "You " as the default text which can be erased just might be the better option. Though, I personally like to have it. If you do make that change, remember to handle the D20 application somehow intelligently; maybe it won't be applied if "You " isn't in front or it uses yet another set of descriptions it will put in front if the "You " is removed.

**Comment by devfag** [comment]
I'll see what I can do

**Comment by devfag** [comment]
I might take a stab at rewriting some of this d20 code anyways: it could be optimized and cleaned up. This would be a good opportunity to do so.

**Comment by devfag** [comment]
Anyways, we should take this to #88

**Pull request merged**
