### PR TITLE
Add /remember and /forget commands for altering permanent AI memory

### PR DESCRIPTION
**Pull request by devfag**
`/remember` takes the sentence following it and feeds it into the end of the prompt
`/forget` opens a menu that displays all the remembered sentences, and the user can select one to delete it from memory

### CODE REVIEW

**Comment by devfag** [comment]
@cloveranon just checking: I saw you gave me collaborator but do you still want me to do PR's?

**Comment by MikkoMMM** [comment]
This might not be linked to this pull request specifically, but I used /prompt to delete every sentence in the starting prompt. Then I proceeded to attempt to edit the entire prompt with a text that didn't end in a period. I saved it and /print showed that the prompt remained empty.

**Comment by devfag** [comment]
Yeah I'm adding some safety checks to prevent that issue. I'll bring those in with this PR

**Comment by MikkoMMM** [comment]
Okay, I've checked the pull request with my Linux machine.

Only one more thing jumped out, which I'll mention even though it probably has nothing to do with the pull request. An empty prompt seems to cause /restart to malfunction:
```
Traceback (most recent call last):
  File "play.py", line 688, in <module>
    play(generator)
  File "play.py", line 506, in play
    story = newStory(generator, story.prompt, context)
  File "play.py", line 286, in newStory
    assert (story.prompt)
AssertionError
```

**Comment by devfag** [comment]
Is this an empty prompt that's been altered or an empty prompt on start?

**Comment by MikkoMMM** [comment]
I tested it with an empty prompt at the start too, and that also caused that issue.

**Comment by devfag** [comment]
Added that fix. Merging soon, just need to fix a few minor formatting issues.

**Comment by MikkoMMM** [comment]
Hmm, I decided to try something more and now after the latest change it seems that when editing the entire prompt, I will have to enter an empty string before it accepts what I had input previously. However, it calls it an invalid prompt.

And the issue I mentioned previously remains that if I try to edit the whole prompt and enter for instance just "Test", the prompt will be empty. I looked at the /print and it's not there.

**Comment by devfag** [comment]
Duh doi. Was a variable name overlap causing a logic error.

**Comment by MikkoMMM** [comment]
Okay, I can exit editing the entire prompt now without pressing enter twice in a row. The other issue still isn't solved; it erases the prompt if I enter just "Test" into the edit the entire prompt screen.

**Comment by devfag** [comment]
Ah, the sentence splitter was discarding 1-word long results. Pushing that fix in a moment.

**Comment by MikkoMMM** [comment]
I can't seem to break the edit entire prompt thing any longer in those ways. It's surprisingly good at recognizing what's a sentence already. Not perfect but then again, this merge will never happen if perfection is demanded. An example of something that is handled incorrectly it would be: "I bought the apples, oranges, etc., but they were all rotten."

**Comment by devfag** [comment]
We can keep tweaking it, but I want to get this merge in before I'm behind on master. Planning on making a new PR for formatting and minor sentence splitting issues.

**Comment by cloveranon** [comment]
> @cloveranon just checking: I saw you gave me collaborator but do you still want me to do PR's?
If you think it's probably free of game breaking bugs than feel free to just push to master.

**Pull request merged**
