### PR TITLE
Story Insert and Summarize Command

### PR DESCRIPTION
**Pull request by devfag**
Story insert (`!`) works the same as thadunge2 fork, where preceding a sentence with an exclamation point will cause it to be interpreted raw by the AI, allowing users to insert their own story content.

`/summarize` works as follows: it copies the current prompt, the current stored memories, and the last result over to the new story. The user is given a prompt to summarize the story that has taken place between the prompt and the last result. The user is then given one last chance to save their existing story, and then the game proceeds as if the player has started a new story with the last result maintained.

### CODE REVIEW

**Comment by AtaIanta** [comment]
>Story insert (!) works the same as thadunge2 fork, where preceding a sentence with an exclamation point will cause it to be interpreted raw by the AI, allowing users to insert their own story content.

Based, I can finally try to make 3rd person story with vanilla gpt model

**Comment by devfag** [comment]
Let me know how that goes.

**Comment by AtaIanta** [comment]
`!` works
image
but doesn't have > at the start after sending an input
in loaded version it has
image
and inputs have two \n after prompt not one even when the action is raw
image

`/summarize` works as intented 


by the way, sorry for asking here but when you load a story in game, you don't get the list of the stories or win10 is shit and does'nt display them
image

**Comment by devfag** [comment]
I don't list the saved stories. I should probably do that.

I removed the `>`, but didn't detect if it's a user line or a narrative line in `print_story`. I'll fix that.

**Comment by AtaIanta** [comment]
`! + vanilla gpt2` is definitely my new favourite play mode
image

**Comment by devfag** [comment]
@Atalanta how much GPU memory does the vanilla gpt-2 use? I'm down to give it a try if my card and run it.

**Comment by AtaIanta** [comment]
the same amount as mormon's model because it's the same but pre-trained
image
image

**Comment by AtaIanta** [comment]
If you are VRAM let and cannot run 1.5B you can try vanilla 774M, it takes 3GB of VRAM.

**Comment by devfag** [comment]
Okay, loading now behaves in a similar manner to the `select_file` function. I also made it so that if you add slashes to your save name, it puts it in a separate directory

**Comment by devfag** [comment]
Before I merge, I want to add one more thing: I want to set up the file listing for both saves and prompts to sort directories first, files second, and I want to add a "random" option to the custom prompts which just picks a random file/directory from the current list. I also am going to add a back option that allows you to go up one level, and if you're on the top level the back option becomes a cancel option.

**Comment by devfag** [comment]
All known bugs fixed. Please review and merge when ready.

**Comment by AIDungeonWiXAnon** [comment]
I wrote out a version of select_file() that merges loading prompts and loading savefiles functionality, since ultimately loading a prompt and a savefile are both just selecting a file and reading them in my eyes.
It doesn't have the extra functionality that you added to select_file() in this PR though, and it will remove load_story(), so I'm looking for your input on merging the functionality of load_story() into select_file() before making a pull request and merging it with the changes you've made here.

**Comment by devfag** [comment]
I would like to consolidate the behaviour since it's basically the same except for the loading part. I'm thinking I'll create a `load_file` function whose only job it is is to load a file, and then a specific function for loading a story and loading a starting prompt. I can then move the `load_file` into utils. I'll see if I can whip that up really quick

**Comment by AIDungeonWiXAnon** [comment]
Agreed, pushing the load functionality into utils as a dedicated function with helper functions for the type of file being loaded sounds like the best route.

**Comment by MikkoMMM** [comment]
The summarize command seemed to print out my summary twice (after saving the previous story into a file).

**Comment by devfag** [comment]
Thanks for pointing that out. Fixed it.

**Pull request merged**
