### PR TITLE
Add support for gpt-neo based models

### PR DESCRIPTION
**Pull request by finetuneanon**
Might not want to merge the README changes as is, but I figured I'd make a PR.

Loading on gpt-neo models on CPU may not work with my HF fork. Not sure, haven't tested. Too slow anyway. Will try to get the less hacky changes included upstream at some point. GPT-2 is still be fine on CPU.

### CODE REVIEW

**Comment by MikkoMMM** [comment]
It seems you've had to change parameters in config.ini, which used to be optimized for GPT-2. How should we reconcile this, offering good defaults for both GPT-2 and GPT-Neo? Of course one low-effort option on our part would be to offer two config files, one of which the user will rename to the actual config.ini, but that sounds hardly ideal.

Also, I've yet to try your changes in practice, but that you seem to have removed a large chunk of gpt2generator.py scares me even without trying it out. It portends to me that you've added GPT-Neo support while removing GPT-2 support. Now, if this were a blank slate repository there'd be no issue with that, but models are large and not always strict upgrades. We have a history using GPT-2. Ehh, well, I should probably investigate further before talking more.

**Comment by finetuneanon** [comment]
For the config, it depends on what you think will be used more. Might be best to keep the original parameters.

I replaced the custom sampling function with huggingface's generate function. It should work with both GPT-2 as well. There's no support for stop tokens, but those weren't used anywhere from what I saw.

**Comment by Meanmelter** [comment]
The changes made to config.ini should be fine. The GPT-2 model should still load and work with Finetuneanon's transformer which fixes the issue with 4.5 version causing irregular VRAM. Most end-users I doubt have `git+` setup to actually pull the file, we may want to throw it on a Mega/Google Drive, update requirements.txt, and then we should be good.

May have to update the youtube tutorial once pushed I think, no big deal.

**Comment by MikkoMMM** [comment]
I've tried this out now. First off, it seems to rely on a very new version of transformers, higher than low-4.x's:

```
  File "/mnt/lvdata/games/AIDungeon2/finetuneanon-Clover/gpt2generator.py", line 9, in <module>
    from transformers import GPT2Tokenizer, GPT2LMHeadModel, GPTNeoForCausalLM
ImportError: cannot import name 'GPTNeoForCausalLM' from 'transformers' (/usr/lib/python3.9/site-packages/transformers/__init__.py)
code 1
```

Okay, we can probably drop support for 2.3.0, but just how far should we go?


I've confirmed that GPT-2 models still work.

But regarding that deleted sample_sequence block in the gpt2generator.py, it wasn't **just** for show. If the user had prompt-toolkit installed, it would show the output of the AI as it was generating it, token by token. Granted, I have heard it didn't do so for at least someone, but it did for me, and I think it's an important feature for those using the CPU in the context of Clover Edition. And even though this might not become an issue with Clover itself, if this code is reused within some other application that generates multiple text outputs at once, even the GPU could be "bottlenecked". However, it's claimed here https://github.com/cloveranon/Clover-Edition/pull/145#issuecomment-830653306 that it's maybe not at least readily apparent how to do this "token by token" generation with the new transformers versions.


Also, regarding the stop_tokens. I think they were used. Line 346 of gpt2generator.py reads:
`self.generate_raw(..., stop_tokens=self.tokenizer.encode(["<|endoftext|>", ">"]), ...)`

generate_raw had only a default value of None, then called self.sample_sequence with `stop_tokens=stop_tokens,`. self.sample_sequence had a default of None but calls the outer sample_sequence with `stop_tokens=stop_tokens,`.

I know it's very confusing. I think the file was in need of refactoring even outside of these modifications.

**Comment by Meanmelter** [comment]
What would be the concern with using newer version of transformers? We have already pushed support for 4.5 which is required for GPT-Neo. I would say we should try to stay on the latest version whenever possible. We should be able to update `gpt2.generator.py` with a `if use_ptoolkit()` and re-add the code.

I can update the changes in a bit if you or Finetuneanon don't get to it first: Trying to see if I can get the customized transformer to install in pip for `requirements.txt` for people who don't already have it installed without the reliant on git+

**Comment by finetuneanon** [comment]
Okay, I wasn't aware of the online output option. Makes sense to keep that then. The conservative approach would be to prune out the changes made to include repetition_penalty_range and slope. Then the generator change isn't necessary either. The old manual approach should still work I believe.

**Comment by MikkoMMM** [comment]
> We have already pushed support for 4.5
The master branch still has a requirement `transformers==2.3.0` and I didn't merge the other pull request either.

I suppose now that we are going to be breaking compatibility already, it's probably fine to go to as late of a version as makes sense. But after that I'd like not asking for the users having to update their transformers library "every time there's an update to Clover".

I didn't quite understand that there was a customized transformer, too. It seemed to work with the regular transformers-4.5.1 package. Custom anything (not by an organization with a good reputation) always makes me slightly skeptical of how it's going to be maintained, and even otherwise a bit untrustful. Why not participate in the main transformers repository, or try to have the things happen on Clover's side of things?

Also, yay! I can run GPT-Neo, too, on my own PC.

**Comment by MikkoMMM** [comment]
I feel like I didn't have this before, but I've now had two occasions where it's interpreted me pressing Enter twice. That is, after giving my input, it reacts to that and then to a "You " input, giving a continuation without asking me. I don't understand why it would do this, since what little modifications there are to play.py, don't seem to have anything to do with input.

**Comment by finetuneanon** [comment]
> Why not participate in the main transformers repository, or try to have the things happen on Clover's side of things?

I already have an issue open there, but looks like it's taking a while. Once that issue is fixed, I'll try to get repetition_penalty improvements merged.

https://github.com/huggingface/transformers/issues/11320

**Comment by Meanmelter** [comment]
Would like to note, that saved files do not seem to work from the old version. I don't think you can save ATM either. New prompts work fine though. I think if we break compatibility for 2.3.0 (Which I think is a good thing going forward given the new models) we should make a function to confirm that the end-user has the proper requirements, and if not then it will update to the proper ones.
I managed to get pip to install the Finetuneanon's transformer, but it seems I can't push the change here.
In addition, I am assuming you both were able to generate legible responses? Mine appear to be gibberish using the official transformer or not. Seems to happen on any model I pick as well. 
error

**Comment by MikkoMMM** [comment]
Yes, I do get legible responses with all the models I've tried thus far. I'm using the official transformer on Python 3.9.3. It seems to save something, but the old saves are going to be missing the new rep-pen-range and rep-pen-slope at the very least for differences.

**Comment by finetuneanon** [comment]
I though I added a try/except, so old saves should load too. Didn't test it tho.

**Comment by Meanmelter** [comment]
OK, I confirmed if I use my CPU my responses are legible. If I use my system GPU no matter what transformer/model I pick it's gibberish like the screenshot.
I got the model to load on my GPU Server and had the same result, didn't matter what transformer/model I was using.
Anyone else with a GPU able to confirm? If it helps you can still load the old GPT-2 Model if the Neo one is too big.

**Comment by finetuneanon** [comment]
Very strange, I used GPU. Does it work without my patches for regular gpt-2?

**Comment by Skhmt** [comment]
It works on my GPU flawlessly.

**Comment by Meanmelter** [comment]
If I go back to the master branch, and install Transformer 2.3.0 it works fine.
I renamed my working directory to .old and made a new copy from this branch, and I run into the issue still.
I do now get this message on story generation `C:\Program Files\Python37\lib\site-packages\transformers\generation_utils.py:965: UserWarning: `max_length` is deprecated in this function, use `stopping_criteria=StoppingCriteriaList(MaxLengthCriteria(max_length=max_length))` instead.
  UserWarning,`
  But I do not think this is related, and only populates on story generation.
  I am not sure why I am getting this message, I am going to update my python and report back

**Comment by Meanmelter** [comment]
OK, upgrading to Python 3.9.4 and installing torch via `pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html` I can now use GPU without weird results. I am not sure if it was the fact I was on torch 1.3.1 or Python 3.7 that caused my issue; I tried to install the previous version of torch but it is not supported on 3.9
I think we will def. need to update requirements in this case.

**Comment by finetuneanon** [comment]
I'm running python 3.7, so my guess would be the torch version.

**Comment by Meanmelter** [comment]
`pip install https://github.com/finetuneanon/transformers/zipball/master` will let you install the modified transformer from the repo without the dependency for git+. I noticed there are some other requirements missing such as other possible torch requirements, I think the default installs for CPU? Might just be for me though.The other two changes I believe that were brought up were to  add a `if use_ptoolkit()` for the previous code brought up from MiKKoMMM for Prompt Toolkit. The other change needed would be to either update the generator or revert to the manual approach for `stop_tokens.`Maybe we need more testing on the last one, I would suspect the manual way may allow people more control over the text that is generated? I would assume the new approach would have some benefit though.
I still can't make any changes to the repo/pull myself so I can't update or make any changes until it's merged, but I do believe I can make all these changes. I would also like to implement some kind of dependency check - that way when future versions of clover come out the client will automatically attempt to update the packages needed with newer versions. I know there is also a separate repo some people used for installing Clover, we may want to try and reach out to the author to have them update as well.

**Comment by MikkoMMM** [comment]
@finetuneanon I suggest giving Meanmelter collaborator privileges on your Clover fork.

**Comment by finetuneanon** [comment]
Invited. I changed the transformers link to use the zipball. The default torch package comes with CUDA on Linux, but I haven't checked for Windows.

**Comment by MikkoMMM** [comment]
Because I have prompt-toolkit on, this error only flashed on the screen, but upon generation of a reply there's this warning:

/usr/lib/python3.9/site-packages/transformers/generation_utils.py:963: UserWarning: \`max_length\` is deprecated in this function, use \`stopping_criteria=StoppingCriteriaList(MaxLengthCriteria(max_length=max_length))\` instead.

I used the modified transformers library.

**Comment by Skhmt** [comment]
@MikkoMMM I'm getting something similar, but I've been testing a massive story:
```
Token indices sequence length is longer than the specified maximum sequence length for this model (2846 > 2048). Running this sequence through the model will result in indexing errors
C:\<...>\site-packages\transformers\generation_utils.py:963: UserWarning: `max_length` is deprecated in this function, use `stopping_criteria=StoppingCriteriaList(MaxLengthCriteria(max_length=max_length))` instead.
  warnings.warn(
```
It cuts off at `warnings.war(`.

**Comment by MikkoMMM** [comment]
Is this from me not having enough VRAM, or are there still problems with the modified transformer? The save was 3624 characters long, so not a huge adventure but also not just a couple of lines.

```
Traceback (most recent call last):
  File "/mnt/lvdata/games/AIDungeon2/finetuneanon-Clover/play.py", line 776, in <module>
    gm.play_story()
  File "/mnt/lvdata/games/AIDungeon2/finetuneanon-Clover/play.py", line 757, in play_story
    if self.process_action(action, suggested_actions):  # End of story
  File "/mnt/lvdata/games/AIDungeon2/finetuneanon-Clover/play.py", line 686, in process_action
    result = self.story.act(action)
  File "/mnt/lvdata/games/AIDungeon2/finetuneanon-Clover/storymanager.py", line 23, in act
    result = self.generator.generate(
  File "/mnt/lvdata/games/AIDungeon2/finetuneanon-Clover/gpt2generator.py", line 297, in generate
    text = self.generate_raw(
  File "/mnt/lvdata/games/AIDungeon2/finetuneanon-Clover/gpt2generator.py", line 258, in generate_raw
    out = self.sample_sequence(
  File "/mnt/lvdata/games/AIDungeon2/finetuneanon-Clover/gpt2generator.py", line 173, in sample_sequence
    generated = self.model.generate(
  File "/usr/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/transformers/generation_utils.py", line 1003, in generate
    return self.sample(
  File "/usr/lib/python3.9/site-packages/transformers/generation_utils.py", line 1520, in sample
    outputs = self(
  File "/usr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.9/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 974, in forward
    transformer_outputs = self.transformer(
  File "/usr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.9/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 858, in forward
    outputs = block(
  File "/usr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.9/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 555, in forward
    attn_outputs = self.attn(
  File "/usr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.9/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 497, in forward
    outputs = self.attention(
  File "/usr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3.9/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 448, in forward
    attn_output, attn_weights = self._attn(
  File "/usr/lib/python3.9/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 277, in _attn
    attn_weights = torch.matmul(query, key.transpose(-1, -2))
RuntimeError: CUDA out of memory. Tried to allocate 2.37 GiB (GPU 0; 11.90 GiB total capacity; 7.51 GiB already allocated; 2.39 GiB free; 8.26 GiB reserved in total by PyTorch)

A fatal error has occurred. 
```

**Comment by Skhmt** [comment]
Mine didn't crash, but it's using a ton more VRAM than before (17 GB instead of like 7)

**Comment by finetuneanon** [comment]
Might have fucked up the way generate is called. Basically max_length should only ever go up to 2048, but I assumed that was taken care of outsite the sampling function.

> Because I have prompt-toolkit on, this error only flashed on the screen, but upon generation of a reply there's this warning:
> 
> /usr/lib/python3.9/site-packages/transformers/generation_utils.py:963: UserWarning: `max_length` is deprecated in this function, use `stopping_criteria=StoppingCriteriaList(MaxLengthCriteria(max_length=max_length))` instead.
> 
> I used the modified transformers library.

This shouldn't happen with my transformers fork. If you modified HEAD transformers, could be because I think they're changing the API. Would also explain why you are OOMing in the _attn function.

**Comment by finetuneanon** [comment]
Think the zipball link doesn't give a zip with the right stuff. I'll change it.

**Comment by Skhmt** [comment]
i uninstalled your zipball's transformers and reinstalled with that link, still getting:
```
Token indices sequence length is longer than the specified maximum sequence length for this model (2846 > 2048). Running this sequence through the model will result in indexing errors
```

**Comment by finetuneanon** [comment]
That issue isn't fixed yet. Need to revert to the old sampling code.

**Comment by Skhmt** [comment]
I don't know, been looking through the code, but I'm new to both python and all of ML, so it has been rough.

**Comment by MNarath1** [comment]
Tried this out locally and while it works it still oom's after like 2-3 inputs on my rtx 2070 with 8 GB VRAM

**Comment by Skhmt** [comment]
So the problem is somewhere in line 53 of gpt2generator.py: `context_tokens = hackyEncode(tokenizer, hackyWhiteSpaceCutter(prompt) + context)`
Which means it's almost definitely in hackyEncode, which is just `tokenizer.encode('====\n ' + s)[2:]`

Adding `truncation=True` or 'only_first' to tokenizer.encode gives weird results. I'm not sure what the [docs](https://huggingface.co/transformers/preprocessing.html) even mean.

**Comment by MNarath1** [comment]
> Tried this out locally and while it works it still oom's after like 2-3 inputs on my rtx 2070 with 8 GB VRAM
> CPU does by the way work but its as slow as you would expect it to be.

ok nevermind redownloading the transformer custom transformer version with the new link seems to have fixed the oom issue it also loads much much faster now

**Comment by finetuneanon** [comment]
If it's just a tokenizer warning it shouldn't cause issues. We can probably suppress it somehow, not sure how thugh. Thanks for tracking it down.

**Comment by Skhmt** [comment]
> If it's just a tokenizer warning it shouldn't cause issues. We can probably suppress it somehow, not sure how thugh. Thanks for tracking it down.

If upgrade from encode to encode_plus (which is the default __call__ as well), just swap out hackyEncode's current line for: `return tokenizer('====\n ' + s, verbose=False).input_ids[2:]` to be functionally the same, but suppress the warning. See [docs](https://huggingface.co/transformers/internal/tokenization_utils.html#transformers.tokenization_utils_base.PreTrainedTokenizerBase.encode_plus).

**Comment by finetuneanon** [comment]
Thanks, I've changed hackyEncode and added back the custom sampling method. I also added the new repetition penalty parameters to it.

**Comment by Skhmt** [comment]
With the revert, I'm getting a:

```
Traceback (most recent call last):
  File "C:\Users\Zen\Desktop\AiDungeon Neo\aidungeon\play.py", line 746, in <module>
    gm.play_story()
  File "C:\Users\Zen\Desktop\AiDungeon Neo\aidungeon\play.py", line 720, in play_story
    if self.process_action(action, suggested_actions):  # End of story
  File "C:\Users\Zen\Desktop\AiDungeon Neo\aidungeon\play.py", line 649, in process_action
    result = self.story.act(action)
  File "C:\Users\Zen\Desktop\AiDungeon Neo\aidungeon\storymanager.py", line 23, in act
    result = self.generator.generate(
  File "C:\Users\Zen\Desktop\AiDungeon Neo\aidungeon\gpt2generator.py", line 379, in generate
    text = self.generate_raw(
  File "C:\Users\Zen\Desktop\AiDungeon Neo\aidungeon\gpt2generator.py", line 340, in generate_raw
    out = self.sample_sequence(
  File "C:\Users\Zen\Desktop\AiDungeon Neo\aidungeon\gpt2generator.py", line 277, in sample_sequence
    out = sample_sequence(
  File "C:\Users\Zen\Desktop\AiDungeon Neo\aidungeon\gpt2generator.py", line 165, in sample_sequence
    logits.scatter_(0, generated, score)
RuntimeError: Expected index [2008] to be smaller than self [50257] apart from dimension 0 and to be smaller size than src [512]
```

**Comment by finetuneanon** [comment]
Should be fixed now.

**Comment by Skhmt** [comment]
Confirmed, VRAM usage much lower now (~7.5GB VRAM) and text seems to print out character by character instead of the whole response at once, which is neat I guess.

**Comment by MikkoMMM** [comment]
Again I tried to make sure I had the latest and greatest transformers modification with
`sudo pip install -r requirements.txt`

Yeah, the text shows up token by token now, but there's still a memory issue for me. The error is the same as in https://github.com/cloveranon/Clover-Edition/pull/147#issuecomment-832493571.

What I did was open up the kornilov text and let the AI continually generate more text by itself.

**Comment by MikkoMMM** [comment]
Loading old saves hasn't been fixed. We are bound to get complaints if something isn't done about that. How about if there's a missing config parameter (any parameter, not just these newly added two), the game looks at the config.ini to use as a default one?

We also need to decide what to do about the defaults for the configuration. The old model seems to produce at least coherent text with these new values, but I'm very bad at distinguishing what's better and what's worse output. What I can say is that the smallest GPT2 model that used to produce abhorrent output (very repetitive use of a few words it has picked) actually writes out full sentences now so that's noticeably better even for someone like me.

**Comment by Skhmt** [comment]
> Again I tried to make sure I had the latest and greatest transformers modification with
> `sudo pip install -r requirements.txt`
> 
> Yeah, the text shows up token by token now, but there's still a memory issue for me. The error is the same as in [#147 (comment)](https://github.com/cloveranon/Clover-Edition/pull/147#issuecomment-832493571).
> 
> What I did was open up the kornilov text and let the AI continually generate more text by itself.

You might have to `pip uninstall transformers` then `pip install https://github.com/finetuneanon/transformers/archive/refs/heads/gpt-neo-dungeon-localattention1.zip`

**Comment by MikkoMMM** [comment]
Hmm, after I uninstalled and reinstalled the gpt-neo-dungeon-localattention1.zip, I've not been able to cause this crash. It seems a bit weird to me since it looked like it was using a cached version:
```
[mikko@localhost finetuneanon-Clover]$ sudo pip uninstall transformers
Found existing installation: transformers 4.6.0.dev0
Uninstalling transformers-4.6.0.dev0:
  Would remove:
    /usr/bin/transformers-cli
    /usr/lib/python3.9/site-packages/transformers-4.6.0.dev0.dist-info/*
    /usr/lib/python3.9/site-packages/transformers/*
Proceed (y/n)? y
  Successfully uninstalled transformers-4.6.0.dev0
[mikko@localhost finetuneanon-Clover]$ sudo pip install https://github.com/finetuneanon/transformers/archive/refs/heads/gpt-neo-dungeon-localattention1.zip
Collecting https://github.com/finetuneanon/transformers/archive/refs/heads/gpt-neo-dungeon-localattention1.zip
  Using cached https://github.com/finetuneanon/transformers/archive/refs/heads/gpt-neo-dungeon-localattention1.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
(A bunch of "Requirement already satisfied"s)
Building wheels for collected packages: transformers
  Building wheel for transformers (PEP 517) ... done
  Created wheel for transformers: filename=transformers-4.6.0.dev0-py3-none-any.whl size=2112854 sha256=9c3e6d247c1f97828b37a374a4d52281533721a57da410c79ea3ad556df5ee2b
  Stored in directory: /root/.cache/pip/wheels/e3/af/54/433d471e839081f009365298244eab5875ce0a1c4c8ca61b21
Successfully built transformers
Installing collected packages: transformers
Successfully installed transformers-4.6.0.dev0
```

What I noticed was that now whenever the VRAM is just about to go over the limit, it falls back down to about where it was when the program was first started.

**Comment by Skhmt** [comment]
Yeah IDK why, but uninstalling then installing worked for me too, whereas every other py package i've used was overwritten with just an install.

**Comment by finetuneanon** [comment]
> Loading old saves hasn't been fixed. We are bound to get complaints if something isn't done about that. How about if there's a missing config parameter (any parameter, not just these newly added two), the game looks at the config.ini to use as a default one?

Do you have a sample for testing?

**Comment by MikkoMMM** [comment]
Just any old one will do. Here:
`{"temp": 0.21, "top-p": 0.8, "top-keks": 0, "rep-pen": 1.2, "context": "This is an example.", "memory": [], "actions": ["Yes, it's an example."], "results": ["Yes, it's an example. Yes, it's an example. Yes, it's an example. Yes, it's an example. Yes, it's an example. . . . . . . . The example is an example. Yes, it's an example. Yes, it's an example."]}`

(Incidentally, that's also a demonstration of the type of output you could expect from the smallest GPT-2 model with the old settings, even if the input was something more meaningful.)

**Comment by finetuneanon** [comment]
Should be fixed.

**Comment by MikkoMMM** [comment]
Seems to work. This feels about ready for a merge, but I'm still not quite sure about how to handle the config. Do we just go with the new values? They don't utterly destroy the ability of the old model to function, at least, but I really can't tell with these things how it compares at a more granular level than that.

**Comment by finetuneanon** [comment]
Maybe a section of the readme could list recommended settings for the older models. Setting rep-pen-range to -1 will disable the the range limit. Think the settings should be fine with gpt-2 too though.

**Comment by Meanmelter** [comment]
Sorry I had been away for some time.

> Seems to work. This feels about ready for a merge, but I'm still not quite sure about how to handle the config. Do we just go with the new values? They don't utterly destroy the ability of the old model to function, at least, but I really can't tell with these things how it compares at a more granular level than that.

It would seem the documentation for this is now missing? I checked Huggingfaces site for 2.3.0 and it's oddly barren https://huggingface.co/transformers/v2.3.0/model_doc/gpt2.html The Wayback Machine from end of 2019 has the same barren results. I am really surprised by this, maybe I have been looking in the wrong spot for this. But I do believe this documentation could shed some light on more granular things. I would suspect that it's merely more control over the output. I am surprised you found improved results with the smaller GPT2 model. I will do some tests to see if it's more coherent with the newer config vs old config.

I also want to work on a dependency-checker for Clover, but I think I'll have to make a separate pull request for it as I do not know when I'll be done with it. I will likely also re-make a Clover Edition installation video once that's all done.

**Comment by Skhmt** [comment]
> Maybe a section of the readme could list recommended settings for the older models. Setting rep-pen-range to -1 will disable the the range limit. Think the settings should be fine with gpt-2 too though.

I've tried it a bunch with GPT-2 and it seems fine to me.

**Comment by Meanmelter** [comment]
> 
> 
> @Meanmelter By config, I mean what's been changed in the config.ini (and possibly also introduction of the new repetition_penalty_range and repetition_penalty_slope).
> 
> Also I noticed that if you remove the v2.3.0/ from your URL, then there's more stuff there.

Oh, like the default values and new options? I would say just go with the new values, they are very easy to change and given the new additions people may want to find a new setting that works with them. Sorry I thought you were still referencing the generation process, which is why I was going to bring up information on V2.3.0. Also if you do remove that from the link it just now references Huggingfaces 4.5.1 version. If people would like to use their own custom config.ini values they can simply merge them, I used to have a copy of mine so I didn't lose changes from Clover when the file got edited for example.

> I've tried it a bunch with the GPT-2 model and it seems fine to me.
I agree, it seems fine (If not slightly more on topic than before)

**Comment by MikkoMMM** [comment]
It seems we are pretty much in an agreement that the new config is good enough to be the default. There will very possibly be people who experiment with them, and then we can add a section into the README for ideas or something like that. And thus I'm merging this.

**Pull request merged**
