### PR TITLE
pytorch, d20, actions

### PR DESCRIPTION
**Pull request by AccidentallyOnPurpose**
Don't accept this yet as I need to make the changes minimal, and fully working.

- [x] pytorch
- [x] suggest actions
- [x] d20

- [ ] colab working
- [ ] pytorch model torrent

### CODE REVIEW

**Comment by cloveranon** [comment]
Git seems to think you've changed every single line. I'm figuring it out.

**Comment by wassname** [comment]
Haha well I originally forked it from AI Dungeon, and then pasted in your code. But yeah I changed a lot!

**Comment by AccidentallyOnPurpose** [comment]
Haha well I originally forked it from AI Dungeon and copied your code in. I also changed a lot

**Comment by AccidentallyOnPurpose** [comment]
You don't have to sort out the conflict if you don't want. If you wait a few days I can do it. 

I didn't originally intend for it to be a PR so I just changes everything like the intro text.

**Comment by cloveranon** [comment]
I can manually merge in the changes to the code. I don't know how to merge the commits through git and keep the commit history and everything.

**Comment by AccidentallyOnPurpose** [comment]
I think I messed up the commit history a bit, so I wouldn't worry about it. Copypasta the parts you like, it definitely saves time.

**Comment by cloveranon** [comment]
Do you have a pytorch model to run this thing? The torrent is not working as far as I can tell. I see some code in hugging face to convert a tensorflow model to pytorch.

**Comment by cloveranon** [comment]
I've manually merged in most of the changes to the branch "pytorch". It currently  only makes it past the initial prompt, and some stuff is still missing, but I'm excited.

**Comment by AccidentallyOnPurpose** [comment]
You can convert the model, but here's a s3 link https://g5gh6hdfg76ikyfghdfgerd.s3-us-west-2.amazonaws.com/model_v5_pytorch.tar.gz

**Comment by AccidentallyOnPurpose** [comment]
An anon pointed out that the pytorch model is 60x slower than it needs to be because it's not reusing hidden states. I couldn't get the tensorflow version running so ony my local PC so I couldn't directly compare. I hope to fix this in the next few days though, shouldn't be to hard, and will make a PR.

One other thing I would like to work on is the failure more where the model start repeating the past action. I find this really hurts playability on long games. One idea I had is to add the action to the repeat penalty, but this make the model almost ignore the prompt. Do you have any ideas for this?

**Comment by AccidentallyOnPurpose** [comment]
BTW nice work merging so quick. That's a lot of code and a lot of changes to look through.

**Comment by cloveranon** [comment]
I didn't merge all of it and not perfectly. Your d20 code is still missing and there's probably bugs.

The repetition penalty is a good idea, it might just need some tweaking of the value.

How is it possible for it to reuse hidden states? I don't think the GPT model is unidirectional. Or do you mean it's allocating new memory every calculation? I looked at the code and it seems to allocate when it's initialized.

**Comment by AccidentallyOnPurpose** [comment]
Oh well it generated one token at a time so it's like
- A
- A 
- A t
- A tr

and so one. It just means that will reuse some of the calculation for the tokens it's already seend.

**Comment by AccidentallyOnPurpose** [comment]
I added the d20 code as a PR, since I wasn't sure if you wanted it. Since you maintaining the repo, I'll go with your preferences on things so as to simplify choices

**Pull request closed without merging**
