### PR TITLE
ANSI Terminal fix

### LINKED ISSUE #102: Colorama not working for input line in Powershell
The Python Colorama package doesn't seem to work with the input line though it works fine for all other lines.
In Powershell:
image

### PR DESCRIPTION
**Pull request by Meanmelter**
This is to fix #102 
If the user is not using Prompt-toolkit or a virtual emulator like Microsofts Windows Terminal (Preview) than we will manually use ctypes to enable ANSI escape sequence processing.

I have done 1 hour of testing no issue.

### CODE REVIEW

**Comment by Meanmelter** [comment]
@Akababa Any chance you could review? I cannot write to this unfortunately.
Hoping I can start looking into other issues.

Also, if you get a chance, could you test it? I noticed my reponse times were like 0.5-1 seconds. Default prompt-toolkit is a good 8 seconds.

**Comment by Meanmelter** [comment]
There might be a better way to implement this; As is it will always execute even if it is not needed. Should be easy to set a flag for it to only run when colorama is installed an python-toolkit is set to off. Now what makes this complicated is figuring out if the end-user has a Virtual Terminal on with those settings...

**Comment by Meanmelter** [comment]
@MikkoMMM Any chance you could review/push?

Sidenote: I am not sure how dedicated you are to making updates/changes but I was thinking on updating the transformer clover uses to a later version: Would let us use GPT-Neo just for example. Not sure if there is any performance gains from 4.5.1 but considering we are on 2.3.0 it may be worth. Then again I don't know how many people are still seeking to this repo for updates. Figured I'd ask here since Clover is pretty decentralized in terms of communication.

**Comment by MikkoMMM** [comment]
I'm not sure if I have what it takes to test this, but I've checked the files and changed ASNI -> ANSI.

I also tried to revert the changes to the config.ini, but I feel like it might be deleting the file entirely because I didn't find anything resembling a revert changes button so I used delete file. This is of course not intentional, and I'd like you to restore it to the main repository's state before I can push. It's "probably okay", I'd say, without more than this eyeing it over.

**Comment by MikkoMMM** [comment]
Ah, yes. Regarding the GPT-Neo and transformer stuff. I'm on board for reviewing and testing those when it's in a state that could be considered for publication.

**Comment by MikkoMMM** [comment]
You know what? I did download your branch to fix my mess. This is what happened when I ran it with prompt-toolkit off:
```
[mikko@localhost Clover-Edition-Modified]$ python play.py 
04/30/2021 22:00:12 - INFO - readline has been imported. This enables a number of editting features but may cause bugs for colab users.
04/30/2021 22:00:12 - INFO - Cuda Available: True    Force CPU: False    Precision: 16-bit

ANSI Terminal Enabled
Traceback (most recent call last):
  File "/mnt/lvdata/games/AIDungeon2/Clover-Edition-Modified/play.py", line 21, in <module>
    kernel32 = ctypes.windll.kernel32
AttributeError: module 'ctypes' has no attribute 'windll'
code 1
```

It seems to at least start up when I modify the line 24 from
`    except ModuleNotFoundError:`
to
`    except:`

Probably not the wisest thing, and I'll let you think of something smarter instead.

**Comment by Meanmelter** [comment]
When you delete the file it just removes the changes, I re-synced from the branch and the files you deleted still show up for me. Thanks for fixing the Typo as well, nice catch. As for GPT-Neo, I was starting to think maybe we should start a new repo? Considering Cloveranon is likely not returning it would be best if we did further work from a new branch that we can modernize while we keep the legacy stuff here to preserve it. We'd both be able to control it and maybe a fresh look and name we could garner interest? We could probably get GPT-Neo working but it may be easier to re-write from scratch. I know the transformer is a bit different but I haven't delved too much into it yet at this point. 

As for the error you got, It is weird ctypes doesn't have windows dll, is this run on a Linux or a colab somewhere? I would suspect that's why it did not work I think. I will make an exception for it in a second.

**Comment by MikkoMMM** [comment]
Merged.

Yeah, it was on my own Arch Linux machine. And I don't think it did just remove the changes but the file as a whole. I had to do push 
[cf5c75c](https://github.com/cloveranon/Clover-Edition/pull/136/commits/cf5c75c276ab60b7d23061475233c6c8ba3f2a05), and that's why you are seeing the config file, I'd say.

I'm not personally very convinced we need another AI Dungeon fork. Clover Edition has a big follower base so we'd have to start from almost scratch with that as well if we started a new fork. However, at least these things could speak for making a new fork:
* If the changes would make the old GPT-2 incompatible (or ensuring compatibility would be a gargantuan task)
* If I couldn't reach Cloveranon. I asked them to give you collaborator privileges and consider what other privilege changes could serve to keep the project alive.

**Comment by Meanmelter** [comment]
> 
> 
> Merged.
> 
> Yeah, it was on my own Arch Linux machine. And I don't think it did just remove the changes but the file as a whole. I had to do push
> [cf5c75c](https://github.com/cloveranon/Clover-Edition/pull/136/commits/cf5c75c276ab60b7d23061475233c6c8ba3f2a05), and that's why you are seeing the config file, I'd say.
> 
> I'm not personally very convinced we need another AI Dungeon fork. Clover Edition has a big follower base so we'd have to start from almost scratch with that as well if we started a new fork. However, at least these things could speak for making a new fork:
> 
>     * If the changes would make the old GPT-2 incompatible (or ensuring compatibility would be a gargantuan task)
> 
>     * If I couldn't reach Cloveranon. I asked them to give you collaborator privileges and consider what other privilege changes could serve to keep the project alive.

Sorry for comment to an old pull request, but I agree with you after the points you brought up.
As it stands, I think you are currently the only one who can collaborate, meaning without you there may never be further updates - Not trying to make it seem like it's your sole responsibility or anything like that, just the state of things assuming the other 3(4?) collaborators never returned. Thanks for reaching out to him. Only way I know how is his email, hopefully he responds if that's how you reached him.

**Pull request merged**
