### PR TITLE
My settings

### PR DESCRIPTION
**Pull request by AtaIanta**
This are the settings which I use, it doesn't give too much random information, for me the colab version of clover is either repeating itself and telling nonsense. Maybe this settings will better, as it works for me locally. We can crank top keks to 40 though. Repetition penalty is too low now, need to go back to 1.2. 

But I need your opinion

### CODE REVIEW

**Comment by Meanmelter** [comment]
I'll test out the settings for awhile.
So far it kind of seems to handle fantasy adventures okay.
I have an RTS story it didn't like to much, kept looping in it.
Lewds aren't too bad though, probably the best type of context so far in terms of responses.

I'll keep testing it out tho.

**Comment by AtaIanta** [comment]
The only issue I have is that an AI tends to ignore information from user input. Sometimes. I wonder if this is the problem with model or the priority to the user input. Maybe we should try implement something to give higher priority to inputs.

**Comment by renekris** [comment]
> The only issue I have is that an AI tends to ignore information from user input.
Yeah, that seems to be a common issue

**Comment by Meanmelter** [comment]
I feel like it does ignore the information I give it more than usual... I think I might test out the original model + Thadunge2 to see if I can reproduce it. Though I don't have enough VRAM to run them properly, so I guess my tests are going to be painfully slow.

**Comment by cloveranon** [comment]
I'm merging this in for now. But do continue your experiments.

I'd really like to abandon top-keks for top-p. They both do approximately the same thing, but the algorithm for top-p seems more elegant. In the end both settings just prevent the AI from doing really unlikely/random things, which is already controlled by temperature. So you may not need either. I put top-keks at 100 and top-p at 0.85 for now, if that doesn't work do change it.

Put word wrap down to 120 because it seemed slightly too wide to my eye but that might just be my terminal/monitor.

**Pull request merged**
